### ISSUE TITLE
Swift 3.0 branch

### ISSUE THREAD

**Issue by jordanekay** [timrwood/SVGPath#4]
I'd like to make a pull request to add [support for Swift 3.0](https://github.com/jordanekay/SVGPath/tree/swift/3.0) to SVGPath. Could you make a `swift/3.0` branch for me to merge into? Thanks!

**Comment by timrwood** [comment]
Hi @jordanekay, there is a branch available now at https://github.com/timrwood/SVGPath/tree/swift/3.0, sorry for the delay.
